# Overt Attention Configuration

camera: "RealSenseCamera"
realignment_threshold: 50
x_offset_to_head_yaw: 0
y_offset_to_head_pitch: 0
robot_topics: "pepperTopics.yaml"
social_attention_mode: "random"
use_sound: false
verbose_mode: false
