# Behavior Controller Configuration
scenario_specification: "lab_tour"
culture_knowledge_base: "cultureKnowledgeBase.yaml"
environment_knowledge_base: "labEnvironmentKnowledgeBase.yaml"
language: "English"
verbose_mode: false