# rag
top_k: 3
verbose: true

# llm
provider: local   # local | openai

# local
local_base_url: "http://localhost:8080/v1"
local_model: "HuggingFaceTB/SmolLM3-3B"
local_api_key: "sk-no-key-required"

# openai
openai_api_key: "sk-xxxx"
openai_model: "gpt-4o-mini"
